[package]
name = "xs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.14", features = ["derive"] }
sqlite = "0.27.0"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"

[dev-dependencies]
indoc = "1.0.7"
